---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgDLousOQ+jLy8qYrJaFhQ7rMzGnGgMMK7BLDJP2vWihIll+vfXQHf0IuEzk7R9IMAe4ceJIWkZoATtC7PFMXTXVKGeijAvm25ptoNZisTuXuHatfsA+phLgRZgut09fOnoP2FAyhG/1Nn6kPRBW5Cx3ryh+cdliNn5F3FRZn6bVHyCLIXiNOP8cRv5p1kFgUiCBBuk6QXM0Hz47fdvmvoC42BrV179m0DbJ4w2qlMtaiXKsuKA7c+Jn51++jID+lRT7/B/5IHASpmOvx1jEzZnKvhhxDRW0YUIqAbAUcCMJDmlSKOAgvDtFEsrs5awoaGg1DY7ZB/aamlQYVr/M62oB85WCmdhP2cAXMhyhMBAyT9w6IITXHTtq+fYvW31yY8QiKmFIVWJ6CcgCXkswO40zODNoHKwLEpcktluJ3BeUg31aKSBQkD60PWsYesd2KwrWK8FIaRaA6iwuPtQVhvZi+Pr6nPNl1oyHM5fHVuazEe9O7kuVHja42+gJoPueqJaRPegCt5jbyh+jPsR+S+JVomKamh29tVxlJidhoV147IZ+9KZZKgFsDPEH9g+PAx/wcJByN75WbB6pcCCA8wxaD/7jlPebsftsicNSoU3qgoKKdq0NzJqWl8UL2rf5fKoVQ91mMh8toTyCtApC8hq43n3zDHBu8qroCn9x/spBBc0CSb1u6b6cOhJpG1I9i4ufBzD0L0kxUlwPeA==
    STRIPE_API_KEY: AgAC5sMERzQ5l+Td8o9N/ocK0/JCeTxoDdqN5OE6j8fOfj2CxUraCvndHXKRmNbHqU2KLb7La7zT4GwaTIItMfLPUxt047yxN9zXHvnynmwEZ9uwVoKJm6By7pmUeJHPtB4nLko0g6blLRbC0sK2AegKOv81QCSFJLs/INB6XdeaHxJG+BzZsd6AarjF/Xi+ORt9DKTmjJJG8wUilCGxvdfJRaGUON1GIBgPJ4S8mpkgx21nedaR+qvsSDZfaxpT6rQbzSlBvXlJTPC4DV6Dc49R5EY66IbBZ/9dI1fVKVbMrYul/RiuwO9pibdDEmTAUvpffyvzdd09bW37yeR6IrnXosD9YVdDvOb4CHuetHg1MReB4UXh7YJLXuULydXc35xRu3eDb5df/kQRBybsDAf1f9O+ogl6PboaGMuAESd2VYYcfh8dajQmrj5ZkRE5tg56nkcHNHn+zfRaVdp3TB5Qs9Ay85TENgEoTfWCWTENggVsUVSWm90Rg9b9n/TYZjuG4qNuycnREcESLq+IwnX5ztz3eG2vby1r8F/nOXyX2HdiZOv+zK/IAgnvFGXU8MEaXXEQNZW/iOfP7uI1mJr907OmwoEtVxl8lr05qjiigmt7+j1NNDuh4hy01vjvaPSbXUBlSRcIC5xPx8OTRTFyY5ue7l1H2u5O90pkGcbHw+oVqyT1PpBSuElOME5qmtbFMJ2Ga2JvVcRiea1ldYifOiSTxrdhKU+LkEGcSg==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
